### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by farisachugthai**
`source/index.rst` was missing one of the documents, specifically `source/RTD.rst`, and an error was emitted as a result.

In addition, building the docs created a lot of extraneous doctrees and as a result, running `git status` was very noisy. Ignore some of these files.

### CODE REVIEW

**Comment by MatthewFlamm** [comment]
Thanks @farisachugthai !

This raises the question of exactly how we generate the documentation pages for serving on GitHub pages.  The default sphinx build does not match the structure required by GitHub pages. I will add this script to this repo, and can you kindly check whether you still need the files added to `.gitignore`?  I don't see these exact folders/files when I generate the documentation on my system.

I think it is a good idea to explicitly add a link to the `rtdpy.RTD` module documentation somewhere for the interested reader.  You can only get to it through one of the other documentation pages currently.  However, the location you've added it is for RTD models, while the RTD module contains mainly the base class to make an RTD model.  I think it makes sense to have a section at the end of the index to handle this case dealing with writing additional RTD models.  A minimal suggestion would be to start with a heading for `Advanced Use` and a toctree with this module.

**Comment by MatthewFlamm** [comment]
I pushed the script I am using to make the documentation and prepare it for GitHub pages in this commit https://github.com/Merck/rtdpy/commit/d16fb4d7232106e11a4bf24e23ad07ce3d406fad

**Comment by farisachugthai** [comment]
Erhm well from the looks of it your script is just a bash script that uses the Makefile. I'm running this on Windows so I can't use the Makefile or bash script itself but looking at it, all it does is run:

`sphinx-build docs source`

which is exactly what I did.

Also what I'm saying is that the RTD document isn't listed in the index, or any one of the toctree directives. The way sphinx works is that if a hyperlink is created to a file but it's not listed in the index, it will generate an error.

If you'd rather create a new toctree that'd work too; however I have generally found it more straightforward to only use 1 and have everything listed there.

**Comment by MatthewFlamm** [comment]
I've never done this on Windows, so if that is the reason to put those lines in `.gitignore` for that reason, that is great with me.

For the toctree, I'm not sure what the ideal scenario is.  On my system it only returns a warning.  The issue I have with the PR state currently is that I put the toctree under a heading called "Included RTD models:".  Im understanding that this isn't the preferred approach.

In this situation, is it preferred to nest the toctree and have it point to RTDmodels.rst and Advanced usage.rst, each of which may have its own toctree, something like this?

**Comment by farisachugthai** [comment]
Ohhhhh I understand now.

So it doesn't matter what heading you put the toctree under. That doesn't change anything. All I'm saying is that because the RTD doc isn't included in any toctree it generates a warning.

If you want to make some new docs called Advanced_Usage.rst and RTDmodels.rst (and btw I would definitely recommend not inserting whitespace in the file name), then you can do so.

So it'd look like

index pointing to ---> Advanced_Usage that has a toctree that points to ---> RTD.rst

or however you want to organize it.

But rather than reorganizing the docs, I think it'd be a lot easier to simply include them all in 1 toctree which is what this PR is for.

**Comment by MatthewFlamm** [comment]
This makes a lot of sense to me now, thanks for putting this project on the right path!  The current structure is not very extendable and makes things too rigid.  After I test this on my system, I will plan on accepting this PR as is.  I will make changes to the structure in a new commit.

**Comment by farisachugthai** [comment]
So I'd only recommend extending the # of toctrees if the number of docs increases substantially. Since most of the docs are just automodule stubs I don't anticipate that happening without massive increases in the documentation but obviously take that with a grain of salt depending on how you want to modify things.

**Comment by MatthewFlamm** [comment]
Looks great to me.  Thanks again and for the great discussion!

I learned a few things in trying to understand this.  And, I have a few ideas for how to further improve the documentation as a result.

**Pull request merged**
